langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: trusty
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: 097495b1-fbec-4ebf-a015-756393a66d0b
  app: dreams-brownfield
  run: rails db:migrate
